dist: xenial
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: J/WlTsndCO2QNeEG+FV3oT+Sj6khV6UuwGPpx1k+YFrHBU+kuinBCkM6gla3w1popmpUKth1PgSeUwsvo9WhU2uhOrLepKxU+kwurBoA+0cAjvksw78135f5rnh3Mb8M3GjrmCt+Q1FBmdLelYUcVHlauw8VHmaMZLfWxMWNDLv8GwCl2KGtwErxFB1csZyNYL6/IhKJXUMtSFDMv36jkEIZafGr1TFOhUQzPpDxAKflzfG7cWXrfQOUo3bASXOeyYiWa4NS6C26bubopW+do7n4m6iLzPyE+tfrMp96tLXyK5MM4LiISfzbqGJ9r46AFX013WgO8bNXtbp4Q8163YXqvF2b0OLk7IzcdBmE4pPUbTAzrItzp+fhCGxKFJfEUERrI/HwtW4xF/AA8Plcd5LIoTkmPLl/ihP4JFJykCHGoOi87FzGoUAcytBuqZS7oYXUA4evSJka52aOMlf3pE3D+4bQJ7PiX5+997OH+whEqfCpM0kCDE2pjrKjORkXHNi8PZl7WrMsn5+pxjuwNhwH4+v/dkXH8MHJ3+Asjxbk7NpMy/6Sx2684yVQsv91NOse3P2vnGos+U6+wdGeLoKJ+APMnKgiYt1LBV7MkIW7TOlm48gTuCduMNdnGrW4yxnf4WQnrWUDXyJiYyPHVm/hKAXbz31jss4cu49GTmU=
  - secure: IKX1wtORuOA9+AO3XR53fELaJ8zmuTyGA4Wimvc7v+HQskkfH2U2jJXEcqW5qkqm2qN4OYDmG+TY7fYf61/GNBMeKo8+xVa6OAcsRVh5ksvKhUXJX8CpEcG4BTI+4tYwExtSZu12VD4XG4d/eplNawZJHWhLgld1sE0ZjKsMQRTJYymzAODR8vgdRfGDwuzuTtTNwL3GKeMQqT2JOrzC4Bwsuaf1lFOcO2qa7sfmsZWrFU1OAThcoHvqeLJ1jVI6T3IuU4Fmi7vtarrc6aOQZy0VpKPXHKUH7PeoX2KVodwqNBgdvJVwDnK/27NbzN+cLcUuPVxFytlnQx8EVD5f0csIdgjB6n3/Eo6FpZov6ypSdkSDhISke4EVbJzcgukdhqac9FwvXgXR0tk6RxAJY4pMPyzEiC7kQkuEQ3G2lHd+2DNt9BXQ4rSZmPzPY+nPd8jnkJsa7ji1RlKx/8qBg6bfXXh580lHI8MYMlOCe5Y8bV1xuafm9vuufxe3+KdAzg3u0K+dQY6e+vYZBew04JPKxNaK/WI4OnGsUYWCJNpV3iO45mxaZ9JkwrJSnmuFFG68ETHB4Di9J7W9covjwInIZwczkhzeItjF/YO4A4/CevVir71XBFOLj9S6itgd0ukWYCNqhz45xOFEdCqVQlYOiz4h6fywhwTNU0VN5gw=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
